#include "ember/eos_cms19.hpp"
#include "ember/eos_composite.hpp"
#include "ember/opacity_aesopus.hpp"
#include "ember/opacity_opal.hpp"
#include "ember/opacity_blend.hpp"
#include "ember/atmosphere.hpp"
#include "ember/boundary.hpp"
#include "ember/constants.hpp"
#include "../examples/lane_emden.hpp"
#include <algorithm>
#include <cmath>
#include <cstdio>

using namespace ember;
static int failures = 0;
static void check(bool ok, const char* label, double value = 0) {
  if (!ok) ++failures;
  std::printf("[%s] %s (%.9g)\n", ok ? "PASS" : "FAIL", label, value);
}

int main() {
  const std::string data = EMBER_DATA_DIR;
  Cms19Eos eos(data + "/eos/cms19_h_tp.dat", data + "/eos/cms19_he_tp.dat", Cms19Eos::Metals::helium_proxy);
  const auto comp = solar_scaled(.7, .02);
  // Independent original TP cells: logT, logP[GPa], logrho, logS[MJ/kg/K].
  for (const auto row : {std::array{1., 3.5, -3., -4.13251, -1.01971},
                         std::array{1., 4.5, 1., -1.45056, -.894136},
                         std::array{0., 3.5, -3., -3.81762, -1.40896},
                         std::array{0., 6.5, 5., .714742, -1.21488}}) {
    const auto c = solar_scaled(row[0], 0);
    const double T = std::pow(10., row[1]), Pg = std::pow(10., row[2] + 10);
    const double Pr = constants::a_rad * std::pow(T, 4) / 3;
    const double rho = eos.rho_from_PT(T, Pg + Pr, c);
    const auto e = eos.eval(T, rho, c);
    check(std::abs(std::log10(rho) - row[3]) < 1e-10,
          "pure component reproduces original TP density cell", rho);
    check(std::abs((e.S - 4 * Pr / (rho * T)) / std::pow(10., row[4] + 10) - 1) < 1e-10,
          "pure component reproduces original entropy with radiation added once");
  }
  {
    // Independent published Y=.275 mixture, not generated by this importer.
    const auto c = solar_scaled(.725, 0);
    const double T = std::pow(10., 4.5), Pg = 1e11;
    const double Pr = constants::a_rad * std::pow(T, 4) / 3;
    const double rho = eos.rho_from_PT(T, Pg + Pr, c);
    const auto e = eos.eval(T, rho, c);
    check(std::abs(std::log10(rho) + 1.35126) < 8e-6,
          "additive-volume mixture agrees with independent CMS19 Y=.275 table");
    check(std::abs(std::log10(e.S - 4 * Pr / (rho * T)) - (10 - .984991)) < 2e-5,
          "mixture entropy includes the published ideal mixing term");
  }
  {
    const auto H = solar_scaled(1, 0), He = solar_scaled(0, 0);
    const auto molecular = eos.eval(1800, 1e-4, H), neutral = eos.eval(3000, 1e-6, He);
    check(std::abs(molecular.P / (constants::R_gas * 1800e-4 / (2 * 1.0078)) - 1) < .02,
          "cold dense hydrogen approaches molecular ideal-gas pressure");
    check(std::abs(neutral.P / (constants::R_gas * 3000e-6 / 4.0026) - 1) < .01,
          "cool helium approaches neutral atomic pressure");
    const auto ionizing = eos.eval(14000, 1e-5, comp);
    check(ionizing.grad_ad < .2 && ionizing.cp > 5e8,
          "partial ionization raises heat capacity and lowers the adiabatic gradient", ionizing.grad_ad);
  }
  {
    constexpr double h = 2e-5;
    double worst = 0;
    for (const auto [lt, lr] : {std::pair{3.371, -6.773}, std::pair{3.731, -4.881},
                               std::pair{4.173, -5.19}, std::pair{4.461, -3.17},
                               std::pair{5.173, -1.177}, std::pair{6.119, .17}, std::pair{6.713, 2.31},
                               std::pair{4.42549, -.931112}, std::pair{5.02878, .058877}}) {
      const double T = std::pow(10., lt), rho = std::pow(10., lr);
      const auto a = eos.eval_with_derivatives(T, rho, comp);
      for (int v = 0; v < 2; ++v) {
        const auto plus = eos.eval(T * std::exp(v == 0 ? h : 0), rho * std::exp(v == 1 ? h : 0), comp);
        const auto minus = eos.eval(T * std::exp(v == 0 ? -h : 0), rho * std::exp(v == 1 ? -h : 0), comp);
        auto compare = [&](double p, double m, double analytic, double scale) {
          const double fd = (p - m) / (2 * h);
          worst = std::max(worst, std::abs(fd - analytic) / std::max({scale, std::abs(fd), std::abs(analytic)}));
        };
        compare(std::log(plus.P), std::log(minus.P), v == 0 ? a.state.chiT : a.state.chiRho, 1);
        compare(plus.cp, minus.cp, v == 0 ? a.dcp_dlnT : a.dcp_dlnRho, a.state.cp);
        compare(plus.delta, minus.delta, v == 0 ? a.ddelta_dlnT : a.ddelta_dlnRho, 1);
        compare(plus.grad_ad, minus.grad_ad, v == 0 ? a.dgrad_ad_dlnT : a.dgrad_ad_dlnRho, 1);
      }
      // The adiabatic direction is independently checked by entropy values.
      const auto& e = a.state;
      const double Pp = e.P * std::exp(h), Tp = T * std::exp(h * e.grad_ad);
      const double Pm = e.P * std::exp(-h), Tm = T * std::exp(-h * e.grad_ad);
      const auto ep = eos.eval(Tp, eos.rho_from_PT(Tp, Pp, comp), comp);
      const auto em = eos.eval(Tm, eos.rho_from_PT(Tm, Pm, comp), comp);
      worst = std::max(worst, std::abs(ep.S - em.S) / (2 * h * e.S));
    }
    check(worst < 2e-5, "pressure, entropy adiabat and transport responses differentiate actual interpolants", worst);
    // This actual dense ionization state has a large source/interpolant
    // consistency defect. Do not silently replace the entropy adiabat by
    // P*delta/(rho*T*cp) to make a Maxwell-identity test pass.
    const double T = std::pow(10., 4.42549), rho = std::pow(10., -.931112);
    const auto e = eos.eval(T, rho, comp);
    const double defect = std::abs(e.P * e.delta / (rho * T * e.cp * e.grad_ad) - 1);
    check(defect > .2 && defect < .3,
          "known dense-ionization Maxwell defect remains visible; EOS is experimental", defect);
  }
  AesopusOpacity low(data + "/opacity/aesopus21_gs98_z020.dat");
  OpalOpacity high(data + "/opacity/opal_gs98_z020.dat");
  BlendedOpacity opacity(low, high, 4.4, 4.5);
  PPChains nuclear;
  Physics physics{&eos, &opacity, &nuclear, 1.9};
  {
    constexpr double h = 2e-5;
    const double T = 3000, g = 2e5;
    GreyAtmosphere atmosphere(eos, opacity, {.tau_top = .001});
    const auto a = atmosphere.eval(T, g, comp);
    const double dt = std::log(atmosphere.eval(T * std::exp(h), g, comp).P
                            / atmosphere.eval(T * std::exp(-h), g, comp).P) / (2 * h);
    const double dg = std::log(atmosphere.eval(T, g * std::exp(h), comp).P
                            / atmosphere.eval(T, g * std::exp(-h), comp).P) / (2 * h);
    check(std::abs(dt - a.dlnP_dlnTeff) < 5e-4 && std::abs(dg - a.dlnP_dlng) < 5e-4,
          "CMS19 atmosphere sensitivities match independent integrations");
    const auto b = GreyAtmosphere(eos, opacity, {.tau_top = .002}).eval(T, g, comp);
    check(std::abs(a.P / b.P - 1) < .001, "doubling the finite top column changes pressure by less than 0.1%", a.P / b.P - 1);
    bool rejected = false;
    try { GreyAtmosphere(eos, opacity).eval(T, g, comp); } catch (const std::domain_error&) { rejected = true; }
    check(rejected, "an atmosphere path below EOS density coverage is rejected");
  }
  {
    double worst = 0;
    for (const auto [lt, lr] : {std::pair{3.43, -6.1}, std::pair{4.31, -5.17},
                               std::pair{5.31, -2.13}, std::pair{6.31, 1.07}}) {
      Model m; m.M = .1 * constants::Msun; m.m = {.4 * m.M, .41 * m.M}; m.comp = {comp, comp};
      m.y = {{std::log(.08 * constants::Rsun), lr * std::log(10.), lt * std::log(10.), .001 * constants::Lsun},
             {std::log(.083 * constants::Rsun), lr * std::log(10.) - .1, lt * std::log(10.) - .04, .0011 * constants::Lsun}};
      const auto a = zone_residual(m, 0, physics, 0), b = zone_residual_numerical(m, 0, physics, 0, nullptr, 1e-5);
      const double dm = m.m[1] - m.m[0];
      for (int k = 0; k < 4; ++k) for (int v = 0; v < 4; ++v) {
        const double scale = dm * (v == 3 ? m.y[0].L : 1) / (k == 2 ? m.y[0].L : 1);
        for (const auto pair : {std::pair{a.dfdy_lo[k][v], b.dfdy_lo[k][v]}, std::pair{a.dfdy_hi[k][v], b.dfdy_hi[k][v]}})
          worst = std::max(worst, std::abs((pair.first - pair.second) * scale) / std::max(1., std::abs(pair.second * scale)));
      }
      bool rejected = false;
      try { zone_residual(m, 0, physics, 1e10, &m); } catch (const std::logic_error&) { rejected = true; }
      check(rejected, "unvalidated caloric energy cannot enter a time-dependent zone");
      rejected = false;
      try { central_residual(m, physics, 1e10, &m); } catch (const std::logic_error&) { rejected = true; }
      check(rejected, "unvalidated caloric energy cannot enter the central energy boundary");
    }
    check(worst < 3e-5, "full stellar zone Jacobian remains consistent with CMS19/pp/MLT/opacity values", worst);
  }
  {
    int rejected = 0;
    Cms19Eos strict(data + "/eos/cms19_h_tp.dat", data + "/eos/cms19_he_tp.dat");
    try { strict.eval(1e6, 1, comp); } catch (const std::domain_error&) { ++rejected; }
    auto he3 = comp; he3[Species::He3] = .001; he3[Species::He4] -= .001;
    try { eos.eval(1e6, 1, he3); } catch (const std::domain_error&) { ++rejected; }
    for (auto [T, rho] : {std::pair{1000., 1e-5}, std::pair{3000., 1e-10}, std::pair{3000., 1000.}, std::pair{1e8, 1.}})
      try { eos.eval(T, rho, comp); } catch (const std::domain_error&) { ++rejected; }
    check(rejected == 6, "composition, extrapolation and cold dense invalid states are rejected", rejected);
    check(!eos.has_internal_energy() && std::isnan(eos.eval(3000, 1e-5, comp).E),
          "missing reliable internal energy is explicit, never a fabricated zero");
  }
  {
    const auto reference = example::lane_emden({.5, 1., 2., 3.}, 1.0);
    double worst = 0;
    for (const auto& a : reference) worst = std::max(worst, std::abs(a.theta - std::sin(a.xi) / a.xi));
    check(worst < 1e-10, "generalized seed Lane-Emden solver matches the independent n=1 solution", worst);
  }
  return failures ? 1 : 0;
}
