#!/usr/bin/env python3
"""Derive timeline values from the plotted track and an explicit decay benchmark."""
import csv
import hashlib
import json
import math
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parent


def main():
    track = ROOT / 'evolution_latest.csv'
    rows = list(csv.DictReader(track.open()))
    peak = max(rows, key=lambda r: float(r['central_Y3']))
    first = next(r for r in rows if float(r['convective_mass_fraction']) < 1 - 1e-6)
    last = rows[-1]
    # A common independent lifetime for ALL baryons is an illustrative model,
    # not an assumption about bound neutrons or a prediction of proton decay.
    solar_mass_g = 1.98847e33
    atomic_mass_g = 1.66053906892e-24
    n0 = 0.1 * solar_mass_g / atomic_mass_g
    log_n = math.log(n0)
    mean_last = log_n + float(np.euler_gamma)  # correction < 1/N0
    percentiles = {str(p): log_n - math.log(-math.log(p)) for p in (.05, .5, .95)}
    mass_loss = {str(f): -math.log1p(-f) for f in (.5, .9, .99, .9999)}
    values = {
        'timelinePeakAge': float(peak['age_yr']) / 1e12,
        'timelinePeakHe': float(peak['central_Y3']),
        'timelineConvectionAge': float(first['age_yr']) / 1e12,
        'timelineConvectionX': float(first['central_X']),
        'timelineLastAge': float(last['age_yr']) / 1e12,
        'timelineLastX': float(last['central_X']),
        'timelineLastTeff': float(last['Teff_K']),
        'timelineLastMean': mean_last,
        'timelineLastLow': percentiles['0.05'],
        'timelineLastHigh': percentiles['0.95'],
    }
    (ROOT / 'lifetime_values.tex').write_text(
        '% Generated by build_lifetime_timeline.py; do not hand-edit.\n' +
        ''.join('\\newcommand{\\%s}{%.4g}\n' % (key, value)
                for key, value in values.items()))
    record = {
        'scope': 'Existing plotted Ember milestones and conditional analytic decay benchmark; no new stellar evolution.',
        'track_sha256': hashlib.sha256(track.read_bytes()).hexdigest(),
        'helium3_peak': peak,
        'first_saved_nonconvective': first,
        'plotted_endpoint': last,
        'benchmark': {
            'assumptions': ['initial baryonic mass 0.1 solar masses',
                            'all baryons independently decay with one constant lifetime',
                            'no accretion, baryon creation, stable daughter baryons or correlated decay',
                            'last event refers to all initially tagged baryons, even after dispersal'],
            'solar_mass_g': solar_mass_g, 'atomic_mass_g': atomic_mass_g,
            'initial_baryon_count_approx': n0,
            'mass_loss_fraction_to_time_over_lifetime': mass_loss,
            'mean_last_time_over_lifetime': mean_last,
            'last_time_quantiles_over_lifetime': percentiles,
            'quantile_method': 'large-N limit of (1-exp(-t/tau))^N; correction O(1/N)',
        },
    }
    # Independent checks on definitions and the survival distribution.
    for loss, u in mass_loss.items():
        assert math.isclose(math.exp(-u), 1 - float(loss), rel_tol=1e-12)
    for p, u in percentiles.items():
        assert math.isclose(math.exp(-math.exp(log_n-u)), float(p), abs_tol=1e-12)
    assert float(first['age_yr']) < float(last['age_yr'])
    record['checks'] = {'fractional_loss_identity': True, 'quantile_cdf_identity': True}
    (ROOT / 'lifetime_benchmarks.json').write_text(json.dumps(record, indent=2) + '\n')

    plt.rcParams.update({'font.size': 9, 'axes.spines.top': False,
                         'axes.spines.right': False, 'pdf.fonttype': 42})
    fig, ax = plt.subplots(1, 2, figsize=(6.8, 2.35), layout='constrained')
    u = np.linspace(0, 10, 400)
    ax[0].semilogy(u, np.exp(-u), color='0.2', lw=1.5)
    ax[0].set(xlabel=r'Time / assumed lifetime, $t_d/\tau_B$',
              ylabel=r'Mean remaining mass, $\langle M_B\rangle/M_{B,0}$',
              xlim=(0, 10), ylim=(1e-5, 1))
    u = np.linspace(125, 136, 500)
    ax[1].plot(u, np.exp(-np.exp(log_n-u)), color='0.2', lw=1.5)
    ax[1].axvspan(percentiles['0.05'], percentiles['0.95'], color='0.7', alpha=.2)
    ax[1].set(xlabel=r'Time / assumed lifetime, $t_d/\tau_B$',
              ylabel='Probability all have decayed',
              xlim=(125, 136), ylim=(0, 1))
    for a in ax:
        a.grid(alpha=.15)
    fig.savefig(ROOT / 'lifetime_decay_reference.pdf', bbox_inches='tight')
    fig.savefig(ROOT / 'lifetime_decay_reference.png', dpi=180, bbox_inches='tight')
    print('Derived timeline values and checked conditional decay identities.')


if __name__ == '__main__':
    main()
