add_executable(ember-info info.cpp)
target_link_libraries(ember-info PRIVATE ember)
add_executable(ember-polytrope polytrope.cpp)
target_link_libraries(ember-polytrope PRIVATE ember)
add_executable(ember-equilibrium equilibrium.cpp)
target_link_libraries(ember-equilibrium PRIVATE ember)
target_compile_definitions(ember-equilibrium PRIVATE EMBER_DATA_DIR="${CMAKE_SOURCE_DIR}/data")
add_executable(ember-evolve evolve.cpp)
target_link_libraries(ember-evolve PRIVATE ember)
target_compile_definitions(ember-evolve PRIVATE EMBER_DATA_DIR="${CMAKE_SOURCE_DIR}/data")
